### ISSUE TITLE
Cannot load app info because app.xml file could not be found, despite it existing

### ISSUE THREAD

**Issue by Mathieu52** [shannah/jdeploy#110]
<img width="791" alt="Capture d’écran, le 2023-08-11 à 16 22 09" src="https://github.com/shannah/jdeploy/assets/47650386/7500e325-ff11-474e-8c4f-5a94e09a09a2">

It was working without any issue about 5 days ago, but now it doesn't work on Mac ARM (Ventura 13.5) and neither does it work on my Windows virtual machines (same error message). I very recently updated my computer OS, but since it doesn't work on Windows either it's probably not that.

### I ran Client4JLauncher from the terminal with the following result :
2023/08/11 16:19:48 Failed to download installer package JSON.  Using default JVM requirements for installer app. Failed to parse json in installer packageInfo%!(EXTRA *json.SyntaxError=unexpected end of JSON input)
2023/08/11 16:19:49 Failed to download installer package JSON.  Using default JVM requirements for installer app. Failed to parse json in installer packageInfo%!(EXTRA *json.SyntaxError=unexpected end of JSON input)
2023/08/11 16:19:49 Failed to download installer package JSON.  Using default JVM requirements for installer app. Failed to parse json in installer packageInfo%!(EXTRA *json.SyntaxError=unexpected end of JSON input)
2023/08/11 16:19:50 Failed to download installer package JSON.  Using default JVM requirements for installer app. Failed to parse json in installer packageInfo%!(EXTRA *json.SyntaxError=unexpected end of JSON input)
2023/08/11 16:19:51 Failed to download installer package JSON.  Using default JVM requirements for installer app. Failed to parse json in installer packageInfo%!(EXTRA *json.SyntaxError=unexpected end of JSON input)
2023/08/11 16:19:51 Failed to download installer package JSON.  Using default JVM requirements for installer app. Failed to parse json in installer packageInfo%!(EXTRA *json.SyntaxError=unexpected end of JSON input)
Redirecting output to /Users/mathieudurand/.jdeploy/log/jdeploy-installer.log

### And that is the content of jdeploy-installer.log : 
Failed to download install files bundle: Server returned HTTP response code: 500 for URL: https://www.jdeploy.com/download.php?code=25DV&version=0.0.0-master&jdeploy_files=true&platform=*
java.io.IOException: Server returned HTTP response code: 500 for URL: https://www.jdeploy.com/download.php?code=25DV&version=0.0.0-master&jdeploy_files=true&platform=*
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at ca.weblite.tools.io.URLUtil.openStream(URLUtil.java:49)
	at ca.weblite.jdeploy.installer.DefaultInstallationContext.downloadJDeployBundleForCode(DefaultInstallationContext.java:134)
	at ca.weblite.jdeploy.installer.DefaultInstallationContext.findInstallFilesDir(DefaultInstallationContext.java:61)
	at ca.weblite.jdeploy.installer.DefaultInstallationContext.findAppXml(DefaultInstallationContext.java:264)
	at ca.weblite.jdeploy.installer.Main.findAppXmlFile(Main.java:347)
	at ca.weblite.jdeploy.installer.Main.loadAppInfo(Main.java:180)
	at ca.weblite.jdeploy.installer.Main.run0(Main.java:507)
	at ca.weblite.jdeploy.installer.Main.run(Main.java:354)
	at ca.weblite.jdeploy.installer.Main.main(Main.java:339)
Found client4.launcher.path property: /Users/mathieudurand/Downloads/karaokeplayer Installer-mac-arm64-@master_25DV 2/karaokeplayer Installer-mac-arm64-@master_25DV.app/Contents/MacOS/Client4JLauncher
java.io.IOException: Cannot load app info because the app.xml file could not be found
	at ca.weblite.jdeploy.installer.Main.loadAppInfo(Main.java:182)
	at ca.weblite.jdeploy.installer.Main.run0(Main.java:507)
	at ca.weblite.jdeploy.installer.Main.run(Main.java:354)
	at ca.weblite.jdeploy.installer.Main.main(Main.java:339)

**Comment by shannah** [comment]
Thanks for reporting this.  Should be fixed now.

**Comment by Mathieu52** [comment]
It's indeed working again, thanks for the quick response and fix!
