### ISSUE TITLE
Can't install Program: "Cannot load app info because the app.xml file could not be found"

### ISSUE THREAD

**Issue by timoreichen** [shannah/jdeploy#157]
It used to be possible (half year before) to install/run builds for windows 11 (only x86 on m1 with parallels). Now, months later, same procedure to deploy it is giving the error above and its not possible to install anymore. I tried out your provided samples,  they too are not possible to install anymore. Nothing to see in the Eventmanager. ?

**Comment by shannah** [comment]
Can you share the app so i can take a look?

**Comment by timoreichen** [comment]
https://www.jdeploy.com/~jdeploy-demo-javafx-ensemble

Windows 11 Pro, latest version now on Parallels, M1. I tried several times
now without luck.

**Comment by timoreichen** [comment]
Can i provide you with logs somehow?

**Comment by shannah** [comment]
Just tried installing that app on Windows 11 - but not in parallels/M1, and it worked ok.

For logs, check the `$HOME/.jdeploy/log/jdeploy-installer.log` file or the `$HOME/.jdeploy/log/jdeploy-installer.lastrun.log` file.

**Comment by timoreichen** [comment]
jdeploy-installer.lastrun.log is empty

jdeply-installer.log:
Found client4.launcher.path property: C:\Mac\Home\Desktop\JavaFX Ensemble 8
Installer 1.0.19.exe
java.io.IOException: Cannot load app info because the app.xml file could
not be found
at ca.weblite.jdeploy.installer.Main.loadAppInfo(Main.java:185)
at ca.weblite.jdeploy.installer.Main.run0(Main.java:515)
at ca.weblite.jdeploy.installer.Main.run(Main.java:362)
at ca.weblite.jdeploy.installer.Main.main(Main.java:351)

It worked so far, till i tried out another time today. What i did was just
removing the app and reinstalled it.

**Comment by shannah** [comment]
Have you renamed the installer file?  It should be named `JavaFX Ensemble 8 Installer-1.0.19_255X.exe`.  But the log indicates that it is named `JavaFX Ensemble 8 Installer-1.0.19.exe`

That little _255X at the end is necessary for it to look up the app metadata.

**Comment by timoreichen** [comment]
Thats it. I see you closed the issue already so thanks for helping!!

For others maybe. I did not rename it - but the browser did (Arc).

**Comment by shannah** [comment]
The browser renamed it?!   What browser are you using?  Can you describe the steps for downloading it, and perhaps share a video?

**Comment by timoreichen** [comment]
https://arc.net/

Open page with it and download.

Quite a nice browser. There is a setting, tidy downloads which removes
'thingis' from (strange) filenames. Quite handy too, i think. Not good for
this case :-)

That said, if possible i would not include needed parameters into the
filename. At least put it in the faq that filenames must not be renamed. I
guess you could encode the parameters somwho into the file properties as
for sure one day a user will rename it too for whatever reason. Which
should be possible.
