### ISSUE TITLE
Colors support for CLI output

### ISSUE THREAD

**Issue by andrii-bodnar** [shannah/jdeploy#16]
Hi,

we are using the Jdeploy library for deploying and running the CLI tool written on Java.

Jdeploy is a great tool and everything is fine except for one little issue with colors.

If I run it as a regular Java application, colors are displayed correctly:

![Screenshot from 2020-12-11 17-43-48](https://user-images.githubusercontent.com/29282228/101923733-75303380-3bd8-11eb-8bdf-d472b67231e8.png)

But if I run it as a command after installation via Jdeploy, colors are disappeared:

![Screenshot from 2020-12-11 17-42-38](https://user-images.githubusercontent.com/29282228/101923813-8c6f2100-3bd8-11eb-8a3e-44760c150123.png)

---

Tried to edit the *jdeploy.js* file and add `--colors` or `--ansi` to the command (`cmd` variable), but it doesn't work:

```
Exception in thread "main" java.lang.RuntimeException: org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --colors
	at ca.weblite.jdeploy.JDeploy.main(JDeploy.java:1174)
Caused by: org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --colors
	at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:347)
	at org.apache.commons.cli.DefaultParser.handleLongOptionWithoutEqual(DefaultParser.java:394)
	at org.apache.commons.cli.DefaultParser.handleLongOption(DefaultParser.java:371)
	at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:239)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
	at ca.weblite.jdeploy.JDeploy.main(JDeploy.java:1145)
```

```
Exception in thread "main" java.lang.RuntimeException: org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --ansi
	at ca.weblite.jdeploy.JDeploy.main(JDeploy.java:1174)
Caused by: org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --ansi
	at org.apache.commons.cli.DefaultParser.handleUnknownToken(DefaultParser.java:347)
	at org.apache.commons.cli.DefaultParser.handleLongOptionWithoutEqual(DefaultParser.java:394)
	at org.apache.commons.cli.DefaultParser.handleLongOption(DefaultParser.java:371)
	at org.apache.commons.cli.DefaultParser.handleToken(DefaultParser.java:239)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:120)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:76)
	at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:60)
	at ca.weblite.jdeploy.JDeploy.main(JDeploy.java:1145)
```

Is there any way to fix this issue?

**Comment by andrii-bodnar** [comment]
@shannah just a friendly reminder :slightly_smiling_face:

**Comment by mddanishansari** [comment]
I had similar issues, you case might be different but this worked for me. I had [Jansi](https://fusesource.github.io/jansi/) in my JAR file, removing `jansi.jar` from my executable JAR helped fix it for me

**Comment by ravn** [comment]
@andrii-bodnar It is your application that behaves differently, which is most likely due to the ANSI library you use not detecting correctly it is being launched from JDeploy.

What ANSI library do you use and how can you configure it to think it is ok in this situation.  Environment variables are typically used for this.

**Comment by andrii-bodnar** [comment]
@ravn thanks a lot for the detailed investigation!
