### ISSUE TITLE
Version 2 release notes

### ISSUE THREAD

**Issue by andrii-bodnar** [shannah/jdeploy#19]
I can see a new versions in the npm package - https://www.npmjs.com/package/jdeploy (2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4)

What was changed? Could you please create releases in this repo with some release notes? It will be helpful a lot

It is a common practice when a new version is released.

**Comment by andrii-bodnar** [comment]
By the way, the new version is breaking my CI/CD:

```
Error: Cannot find module 'njre'
Require stack:
- /home/runner/work/crowdin-cli/crowdin-cli/jdeploy-bundle/jdeploy.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/crowdin-cli/crowdin-cli/jdeploy-bundle/jdeploy.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND'
```

So I had to explicitly use the 1.0.22

**Comment by shannah** [comment]
Thanks.  This has been a bit of a rocky upgrade... Still sorting some things out with the publish process.  Will have this corrected shortly.
