### ISSUE TITLE
Installed application crashes on startup: Failed to run update command.

### ISSUE THREAD

**Issue by pikdum** [shannah/jdeploy#28]
Probably doing something wrong on my end of things, just trying things out.

Platform: Ubuntu 21.10
Java: openjdk 17.0.1 2021-10-19
Node: v16.14.0

Made a basic Clojure GUI app following a bit of https://gist.github.com/daveray/1441520, and built it as a .jar:
* https://github.com/pikdum/pikdum-test-app
* https://www.jdeploy.com/~pikdum-test-app

It works when running with `java -jar target/test-app-0.1.0-SNAPSHOT.jar`, but not when trying to run the jdeploy installed version.
Tried tweaking a few things like java version, but no luck.

Update: this happens with both the .deb and .bin, but it works as expected when running through `npm`.

```
2022/02/15 00:54:00 In Launch().  The app is Not loaded yet
2022/02/15 00:54:00 There was a problem parsing the string 
2022/02/15 00:54:00 strconv.ParseInt: parsing "": invalid syntax
2022/02/15 00:54:00 We got through this
Size is -1
Content length -1
2022/02/15 00:54:01 There was a problem parsing the string 
2022/02/15 00:54:01 strconv.ParseInt: parsing "": invalid syntax
2022/02/15 00:54:01 We got through this
Size is -1
Content length -1
2022/02/15 00:54:01 About to install app

Size is -1
Content length -1
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x382d46 pc=0x7fa89f7fdf3d]

runtime stack:
runtime.throw({0x557cdb12e4cd, 0x557cdb78cf03})
	/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/signal_unix.go:719 +0x396

goroutine 17 [syscall, locked to thread]:
runtime.cgocall(0x557cdb11d246, 0xc00017fba0)
	/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/cgocall.go:156 +0x5c fp=0xc00017fb78 sp=0xc00017fb40 pc=0x557cdae7d49c
github.com/shannah/client4jgo._Cfunc_StartProgress()
	_cgo_gotypes.go:107 +0x45 fp=0xc00017fba0 sp=0xc00017fb78 pc=0x557cdb11ac65
github.com/shannah/client4jgo.StartProgress(...)
	/home/runner/work/client4jgo/client4jgo/gtk_progress_dialog.go:15
github.com/shannah/client4jgo.(*SplashView).Run(0xc000540960)
	/home/runner/work/client4jgo/client4jgo/splashview_empty.go:23 +0x1e fp=0xc00017fbc0 sp=0xc00017fba0 pc=0x557cdb1196fe
github.com/shannah/client4jgo.LaunchApp({{0x0, 0x0}, {0x0, 0x0}, {0xc0001282c0, 0xa6}, {0x0, 0x0}, {0xc00001c530, 0xf}, ...}, ...)
	/home/runner/work/client4jgo/client4jgo/launch_controller.go:438 +0x41f fp=0xc00017fc80 sp=0xc00017fbc0 pc=0x557cdb11157f
main.main1(0x1)
	/home/runner/work/client4jgo/client4jgo/launcher/mainweb.go:57 +0x205 fp=0xc00017fe18 sp=0xc00017fc80 pc=0x557cdb11c345
main.Update(...)
	/home/runner/work/client4jgo/client4jgo/launcher/mainweb.go:20
_cgoexp_2cec8f1074d8_Update(0x557cdb20c648)
	_cgo_gotypes.go:42 +0x1e fp=0xc00017fe30 sp=0xc00017fe18 pc=0x557cdb11c45e
runtime.cgocallbackg1(0x557cdb11c440, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/cgocall.go:306 +0x29a fp=0xc00017ff00 sp=0xc00017fe30 pc=0x557cdae7d97a
runtime.cgocallbackg(0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/cgocall.go:232 +0x109 fp=0xc00017ff90 sp=0xc00017ff00 pc=0x557cdae7d649
runtime.cgocallbackg(0x557cdb11c440, 0x7fff18ef204f, 0x0)
	<autogenerated>:1 +0x31 fp=0xc00017ffb8 sp=0xc00017ff90 pc=0x557cdaedecb1
runtime.cgocallback(0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:915 +0xb3 fp=0xc00017ffe0 sp=0xc00017ffb8 pc=0x557cdaedc893
runtime.goexit()
	/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00017ffe8 sp=0xc00017ffe0 pc=0x557cdaedcac1

goroutine 54 [select, locked to thread]:
net/http.(*http2ClientConn).RoundTrip(0xc00020a000, 0xc000210200)
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:7697 +0x46b
net/http.(*http2Transport).RoundTripOpt(0xc00016c150, 0xc000210200, {0xc0})
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:7106 +0x1b7
net/http.(*http2Transport).RoundTrip(...)
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:7067
net/http.http2noDialH2RoundTripper.RoundTrip({0x557cdb3bc200}, 0xc000210200)
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:9453 +0x1b
net/http.(*Transport).roundTrip(0x557cdb3bc200, 0xc000210200)
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/transport.go:539 +0x390
net/http.(*Transport).RoundTrip(0x30, 0x557cdb20f940)
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/roundtrip.go:18 +0x19
net/http.send(0xc000210200, {0x557cdb20f940, 0x557cdb3bc200}, {0x557cdb202520, 0x1, 0x0})
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc0002c5ad0, 0xc000210200, {0xc000210200, 0x2f, 0x0})
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc0002c5ad0, 0xc000210200)
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/client.go:593
github.com/shannah/client4jgo.downloadFile({0xc00031e140, 0x46}, {0xc000017278, 0x17}, 0xc0000a7280)
	/home/runner/work/client4jgo/client4jgo/httpfuncs.go:63 +0xb7
github.com/shannah/client4jgo.npmDownloadTarball({0xc00001c530, 0xf}, {0xc0000b2dc5, 0x5}, 0x557cdaf2ce85)
	/home/runner/work/client4jgo/client4jgo/npm.go:660 +0x369
github.com/shannah/client4jgo.InstallApp(0xc00020c000)
	/home/runner/work/client4jgo/client4jgo/launch_controller.go:568 +0x23b
github.com/shannah/client4jgo.LaunchApp.func1()
	/home/runner/work/client4jgo/client4jgo/launch_controller.go:293 +0x112
created by github.com/shannah/client4jgo.LaunchApp
	/home/runner/work/client4jgo/client4jgo/launch_controller.go:437 +0x413

goroutine 52 [IO wait]:
internal/poll.runtime_pollWait(0x7fa89c706798, 0x72)
	/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc0000d0280, 0xc000364500, 0x0)
	/opt/hostedtoolcache/go/1.17.6/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.17.6/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0000d0280, {0xc000364500, 0x220e, 0x220e})
	/opt/hostedtoolcache/go/1.17.6/x64/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0000d0280, {0xc000364500, 0xc0003650ad, 0x19})
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc000194000, {0xc000364500, 0x1661, 0xc00011d7f8})
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0004e2030, {0xc000364500, 0x0, 0x557cdae83a8d})
	/opt/hostedtoolcache/go/1.17.6/x64/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc000198278, {0x557cdb20f300, 0xc0004e2030})
	/opt/hostedtoolcache/go/1.17.6/x64/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000198000, {0x557cdb20f8c0, 0xc000194000}, 0x166e)
	/opt/hostedtoolcache/go/1.17.6/x64/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc000198000, 0x0)
	/opt/hostedtoolcache/go/1.17.6/x64/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
	/opt/hostedtoolcache/go/1.17.6/x64/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc000198000, {0xc0001c7000, 0x1000, 0xc000083040})
	/opt/hostedtoolcache/go/1.17.6/x64/src/crypto/tls/conn.go:1277 +0x16f
bufio.(*Reader).Read(0xc00018e1e0, {0xc00054c038, 0x9, 0xc00058f1a0})
	/opt/hostedtoolcache/go/1.17.6/x64/src/bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x557cdb20f1c0, 0xc00018e1e0}, {0xc00054c038, 0x9, 0x9}, 0x9)
	/opt/hostedtoolcache/go/1.17.6/x64/src/io/io.go:328 +0x9a
io.ReadFull(...)
	/opt/hostedtoolcache/go/1.17.6/x64/src/io/io.go:347
net/http.http2readFrameHeader({0xc00054c038, 0x9, 0xc0004de030}, {0x557cdb20f1c0, 0xc00018e1e0})
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:1555 +0x6e
net/http.(*http2Framer).ReadFrame(0xc00054c000)
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:1813 +0x95
net/http.(*http2clientConnReadLoop).run(0xc00011df98)
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:8608 +0x130
net/http.(*http2ClientConn).readLoop(0xc00020a000)
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:8531 +0x6f
created by net/http.(*http2Transport).newClientConn
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:7325 +0xb85

goroutine 28 [select]:
net/http.(*http2clientStream).writeRequest(0xc000196300, 0xc000210200)
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:7865 +0xaa8
net/http.(*http2clientStream).doRequest(0x557cdb061d26, 0xc0000ed678)
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:7727 +0x1e
created by net/http.(*http2ClientConn).RoundTrip
	/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:7656 +0x30f
2022/02/15 00:54:01 Failed to launch app. %!(EXTRA *errors.errorString=Failed to update app.%!(EXTRA *errors.errorString=Failed to run update command. %!(EXTRA *exec.ExitError=signal: aborted (core dumped))))
```

**Comment by shannah** [comment]
This should be fixed in the latest release.  Please try downloading the demos again and let me know if it still fails for you.
