### ISSUE TITLE
Swingset demo fails to install on Garuda (Arch)

### ISSUE THREAD

**Issue by geoffbeier** [shannah/jdeploy#29]
When I tried the SwingSet demo from the site, there was a brief attempt to show a window, then a segfault:

```
2022/02/15 08:43:10 In Launch().  The app is Not loaded yet
2022/02/15 08:43:10 We got through this
Size is -1
Content length -1
2022/02/15 08:43:11 We got through this
Size is -1
Content length -1
2022/02/15 08:43:12 About to install app

Size is -1
Content length -1
Size is 14820019
Content length 14820019
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x382d46 pc=0x7f3839d614bd]

runtime stack:
runtime.throw({0x5558e245f4cd, 0x0})
/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/signal_unix.go:719 +0x396

goroutine 17 [syscall, locked to thread]:
runtime.cgocall(0x5558e244e246, 0xc0001f1ba0)
/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/cgocall.go:156 +0x5c fp=0xc0001f1b78 sp=0xc0001f1b40 pc=0x5558e21ae49c
github.com/shannah/client4jgo._Cfunc_StartProgress()
_cgo_gotypes.go:107 +0x45 fp=0xc0001f1ba0 sp=0xc0001f1b78 pc=0x5558e244bc65
github.com/shannah/client4jgo.StartProgress(...)
/home/runner/work/client4jgo/client4jgo/gtk_progress_dialog.go:15
github.com/shannah/client4jgo.(*SplashView).Run(0xc00063f410)
/home/runner/work/client4jgo/client4jgo/splashview_empty.go:23 +0x1e fp=0xc0001f1bc0 sp=0xc0001f1ba0 pc=0x5558e244a6fe
github.com/shannah/client4jgo.LaunchApp({{0xc00001a3f0, 0x11}, {0x0, 0x0}, {0xc000214f00, 0x24de}, {0x0, 0x0}, {0xc00001a420, 0x11}, ...}, ...)
/home/runner/work/client4jgo/client4jgo/launch_controller.go:438 +0x41f fp=0xc0001f1c80 sp=0xc0001f1bc0 pc=0x5558e244257f
main.main1(0x1)
/home/runner/work/client4jgo/client4jgo/launcher/mainweb.go:57 +0x205 fp=0xc0001f1e18 sp=0xc0001f1c80 pc=0x5558e244d345
main.Update(...)
/home/runner/work/client4jgo/client4jgo/launcher/mainweb.go:20
_cgoexp_2cec8f1074d8_Update(0x5558e253d648)
_cgo_gotypes.go:42 +0x1e fp=0xc0001f1e30 sp=0xc0001f1e18 pc=0x5558e244d45e
runtime.cgocallbackg1(0x5558e244d440, 0x0, 0x0)
/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/cgocall.go:306 +0x29a fp=0xc0001f1f00 sp=0xc0001f1e30 pc=0x5558e21ae97a
runtime.cgocallbackg(0x0, 0x0, 0x0)
/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/cgocall.go:232 +0x109 fp=0xc0001f1f90 sp=0xc0001f1f00 pc=0x5558e21ae649
runtime.cgocallbackg(0x5558e244d440, 0x7ffe0645ad3f, 0x0)
<autogenerated>:1 +0x31 fp=0xc0001f1fb8 sp=0xc0001f1f90 pc=0x5558e220fcb1
runtime.cgocallback(0x0, 0x0, 0x0)
/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:915 +0xb3 fp=0xc0001f1fe0 sp=0xc0001f1fb8 pc=0x5558e220d893
runtime.goexit()
/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0001f1fe8 sp=0xc0001f1fe0 pc=0x5558e220dac1

goroutine 13 [sync.Cond.Wait, locked to thread]:
sync.runtime_notifyListWait(0xc000116348, 0x48)
/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/sema.go:513 +0x13d
sync.(*Cond).Wait(0xc000096600)
/opt/hostedtoolcache/go/1.17.6/x64/src/sync/cond.go:56 +0x8c
net/http.(*http2pipe).Read(0xc000116330, {0xc0002f4000, 0x8000, 0x8000})
/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:3618 +0xeb
net/http.http2transportResponseBody.Read({0x0}, {0xc0002f4000, 0x5558e2262894, 0xc0000c2038})
/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:8890 +0x85
github.com/shannah/client4jgo.(*reader).Read(0xc0000ec5d0, {0xc0002f4000, 0xc0000918a0, 0xc0000918a0})
/home/runner/work/client4jgo/client4jgo/httpfuncs.go:42 +0x32
io.copyBuffer({0x5558e2541440, 0xc0000918a0}, {0x5558e2540740, 0xc0000ec5d0}, {0x0, 0x0, 0x0})
/opt/hostedtoolcache/go/1.17.6/x64/src/io/io.go:423 +0x1b2
io.Copy(...)
/opt/hostedtoolcache/go/1.17.6/x64/src/io/io.go:382
os.genericReadFrom(0x5558e2212dfe, {0x5558e2540740, 0xc0000ec5d0})
/opt/hostedtoolcache/go/1.17.6/x64/src/os/file.go:162 +0x5d
os.(*File).ReadFrom(0xc0000c2038, {0x5558e2540740, 0xc0000ec5d0})
/opt/hostedtoolcache/go/1.17.6/x64/src/os/file.go:156 +0x1b0
io.copyBuffer({0x5558e2540b20, 0xc0000c2038}, {0x5558e2540740, 0xc0000ec5d0}, {0x0, 0x0, 0x0})
/opt/hostedtoolcache/go/1.17.6/x64/src/io/io.go:409 +0x14b
io.Copy(...)
/opt/hostedtoolcache/go/1.17.6/x64/src/io/io.go:382
github.com/shannah/client4jgo.downloadFile({0xc00014c280, 0x4a}, {0xc000092618, 0x17}, 0xc0000a6080)
/home/runner/work/client4jgo/client4jgo/httpfuncs.go:79 +0x2e8
github.com/shannah/client4jgo.npmDownloadTarball({0xc00001a420, 0x11}, {0xc00001cb35, 0x5}, 0x5558e225de85)
/home/runner/work/client4jgo/client4jgo/npm.go:660 +0x369
github.com/shannah/client4jgo.InstallApp(0xc000230000)
/home/runner/work/client4jgo/client4jgo/launch_controller.go:568 +0x23b
github.com/shannah/client4jgo.LaunchApp.func1()
/home/runner/work/client4jgo/client4jgo/launch_controller.go:293 +0x112
created by github.com/shannah/client4jgo.LaunchApp
/home/runner/work/client4jgo/client4jgo/launch_controller.go:437 +0x413

goroutine 11 [IO wait]:
internal/poll.runtime_pollWait(0x7f3834444798, 0x72)
/opt/hostedtoolcache/go/1.17.6/x64/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc0000ce280, 0xc000458c83, 0x0)
/opt/hostedtoolcache/go/1.17.6/x64/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
/opt/hostedtoolcache/go/1.17.6/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0000ce280, {0xc000458c83, 0x9604, 0x9604})
/opt/hostedtoolcache/go/1.17.6/x64/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0000ce280, {0xc000458c83, 0xd, 0xc0000b9e00})
/opt/hostedtoolcache/go/1.17.6/x64/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc000114000, {0xc000458c83, 0x5558e232ee39, 0xc0001957f8})
/opt/hostedtoolcache/go/1.17.6/x64/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0001384f8, {0xc000458c83, 0x0, 0x5558e21b4a8d})
/opt/hostedtoolcache/go/1.17.6/x64/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc000118278, {0x5558e2540300, 0xc0001384f8})
/opt/hostedtoolcache/go/1.17.6/x64/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000118000, {0x5558e25408c0, 0xc000114000}, 0xc00045802a)
/opt/hostedtoolcache/go/1.17.6/x64/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc000118000, 0x0)
/opt/hostedtoolcache/go/1.17.6/x64/src/crypto/tls/conn.go:651 +0xb06
crypto/tls.(*Conn).readRecord(...)
/opt/hostedtoolcache/go/1.17.6/x64/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc000118000, {0xc0001f2000, 0x1000, 0x5558e238f946})
/opt/hostedtoolcache/go/1.17.6/x64/src/crypto/tls/conn.go:1277 +0x16f
bufio.(*Reader).Read(0xc0004e5620, {0xc0006368f8, 0x9, 0x0})
/opt/hostedtoolcache/go/1.17.6/x64/src/bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x5558e25401c0, 0xc0004e5620}, {0xc0006368f8, 0x9, 0x9}, 0x9)
/opt/hostedtoolcache/go/1.17.6/x64/src/io/io.go:328 +0x9a
io.ReadFull(...)
/opt/hostedtoolcache/go/1.17.6/x64/src/io/io.go:347
net/http.http2readFrameHeader({0xc0006368f8, 0x9, 0xc00063e600}, {0x5558e25401c0, 0xc0004e5620})
/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:1555 +0x6e
net/http.(*http2Framer).ReadFrame(0xc0006368c0)
/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:1813 +0x95
net/http.(*http2clientConnReadLoop).run(0xc000195f98)
/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:8608 +0x130
net/http.(*http2ClientConn).readLoop(0xc00022e000)
/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:8531 +0x6f
created by net/http.(*http2Transport).newClientConn
/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:7325 +0xb85

goroutine 26 [select]:
net/http.(*http2clientStream).writeRequest(0xc000116300, 0xc000140200)
/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:7865 +0xaa8
net/http.(*http2clientStream).doRequest(0x0, 0xc00003d678)
/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:7727 +0x1e
created by net/http.(*http2ClientConn).RoundTrip
/opt/hostedtoolcache/go/1.17.6/x64/src/net/http/h2_bundle.go:7656 +0x30f
2022/02/15 08:43:13 Failed to launch app. %!(EXTRA *errors.errorString=Failed to update app.%!(EXTRA *errors.errorString=Failed to run update command. %!(EXTRA *exec.ExitError=signal: aborted (core dumped))))
```

**Comment by shannah** [comment]
Thanks for reporting this.  I'm guessing this is the same issue as https://github.com/shannah/jdeploy/issues/28 and https://github.com/shannah/jdeploy/issues/25
Probably there is a GTK library dependency that isn't installed.   I'm setting up an Arch box today, and am hopeful I can reproduce it.

**Comment by shannah** [comment]
Also https://github.com/shannah/jdeploy/issues/30

**Comment by shannah** [comment]
This should be fixed in the latest release.  Please try downloading the demos again and let me know if it still fails for you.

**Comment by geoffbeier** [comment]
That fixed it here!
