### ISSUE TITLE
SwingSet2 and JavaFX Ensemble samples are crashing on Slackware 15

### ISSUE THREAD

**Issue by sanel** [shannah/jdeploy#30]
Hi,

I have a fresh, Slackware 15 (gtk 3.24.31 and 4.4.1), installation and both demos are crashing with core dump. I've downloaded `.bin` files.  Here is the output for SwingSet2:

```
$ ./SwingSet2\ Installer-1.0.5_255W.bin 
2022/02/15 15:45:53 In Launch().  The app is Not loaded yet
2022/02/15 15:45:53 We got through this
Size is -1
Content length -1
2022/02/15 15:45:53 We got through this
Size is -1
Content length -1
2022/02/15 15:45:53 About to install app

Size is -1
Content length -1

(SwingSet2 Installer-1.0.5_255W.bin:27106): GLib-GObject-CRITICAL **: 15:45:53.729: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed

(SwingSet2 Installer-1.0.5_255W.bin:27106): GLib-GObject-CRITICAL **: 15:45:53.729: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed

(SwingSet2 Installer-1.0.5_255W.bin:27106): GLib-GObject-CRITICAL **: 15:45:53.729: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed

(SwingSet2 Installer-1.0.5_255W.bin:27106): dbind-WARNING **: 15:45:53.733: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
free(): invalid pointer
2022/02/15 15:45:53 Failed to launch app. %!(EXTRA *errors.errorString=Failed to update app.%!(EXTRA *errors.errorString=Failed to run update command. %!(EXTRA *exec.ExitError=signal: aborted (core dumped))))
```

This is backtrace from a core dump, run with `gdb ./SwingSet2\ Installer-1.0.5_255W.bin ./core`

```(gdb) bt
#0  0x00007fbf4fd5e868 in raise () at /lib64/libc.so.6
#1  0x00007fbf4fd45546 in abort () at /lib64/libc.so.6
#2  0x00007fbf4fda4278 in  () at /lib64/libc.so.6
#3  0x00007fbf4fdac69a in  () at /lib64/libc.so.6
#4  0x00007fbf4fdae09c in _int_free () at /lib64/libc.so.6
#5  0x00007fbf4fdb1d14 in free () at /lib64/libc.so.6
#6  0x0000557df1b89cd7 in _jdeploy_gtk_progress_update ()
#7  0x00007fbf500ebc69 in  () at /usr/lib64/libgdk-3.so.0
#8  0x00007fbf4ff7f504 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#9  0x00007fbf4ff7f868 in  () at /usr/lib64/libglib-2.0.so.0
#10 0x00007fbf4ff7f90f in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#11 0x00007fbf503a65c1 in gtk_main_iteration_do () at /usr/lib64/libgtk-3.so.0
#12 0x0000557df1b8a02d in StartProgress ()
#13 0x0000557df1b8a268 in _cgo_54909660d3e3_Cfunc_StartProgress ()
#14 0x0000557df1949788 in runtime.asmcgocall.abi0 ()
#15 0x00007ffc23f51508 in  ()
#16 0x0000557df19252d8 in runtime.newproc.func1 ()
#17 0x000000c000344060 in  ()
#18 0x0a007fbf4c52a8e8 in  ()
#19 0x00007ffc23f51508 in  ()
#20 0x00000000000004c8 in  ()
#21 0x000000c000000680 in  ()
#22 0x000000c0001f3bb0 in  ()
#23 0x0000557df1947886 in runtime.systemstack.abi0 ()
#24 0x00007ffc23f51518 in  ()
#25 0x0000000000000000 in  ()
```

**Comment by shannah** [comment]
Thanks.  Getting lots of reports on Linux.  Looking into it.  Probably there is a GTK library dependency that I *thought* was standard, but is not...

https://github.com/shannah/jdeploy/issues/28
https://github.com/shannah/jdeploy/issues/29

**Comment by shannah** [comment]
This should be fixed in the latest release.  Please try downloading the demos again and let me know if it still fails for you.
