### ISSUE TITLE
Runtime.getRuntime().exec doesn't work

### ISSUE THREAD

**Issue by theapache64** [shannah/jdeploy#36]
When running JAR directly, `Runtime.getRuntime().exec("git")` works, but running via the installed command, it doesn't work.

```
Exception in thread "main" java.io.IOException: Cannot run program "git": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at java.base/java.lang.Runtime.exec(Unknown Source)
        at java.base/java.lang.Runtime.exec(Unknown Source)
``` 

Any idea?

**Comment by shannah** [comment]
What operating system? Is it a GUI app, or are you running through the CLI?  Installed via `npm install` or via double-clickable desktop installer?

Are both running in same terminal environment? (in same terminal window)?

**Comment by theapache64** [comment]
> What operating system?
macOS
> Is it a GUI app, or are you running through the CLI? 
CLI
> Installed via npm install or via double-clickable desktop installer?
Installed via `sudo jdeploy install`

> Are both running in same terminal environment? (in same terminal window)?
Yes

**Comment by theapache64** [comment]
Both are same. Confirm

**Comment by theapache64** [comment]
UPDATE: The issue is not there in [1.022](https://www.npmjs.com/package/jdeploy/v/1.0.22)

**Comment by theapache64** [comment]
Yes.

**Comment by shannah** [comment]
Those will be different versions of java.

Please post output of both system properties and env vars printed from inside the java app.
