### ISSUE TITLE
cant add filetypes using the GUI

### ISSUE THREAD

**Issue by electronstudio** [shannah/jdeploy#43]
When I click the '+' button to add a filetype:

```
Exception in thread "AWT-EventQueue-0" org.json.JSONException: JSONObject["documentTypes"] not found.
        at org.json.JSONObject.get(JSONObject.java:580)
        at org.json.JSONObject.getJSONArray(JSONObject.java:773)
        at ca.weblite.jdeploy.gui.JDeployProjectEditor.lambda$initMainFields$27(JDeployProjectEditor.java:862)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by shannah** [comment]
This should have been fixed already.  https://github.com/shannah/jdeploy/issues/39

Try updating jDeploy.

**Comment by electronstudio** [comment]
I'm not sure how to check for sure which version I'm on, `jdeploy --version` doesn't work, but I think I'm on the latest:

    > sudo npm list -g jdeploy
    /usr/lib
    └── jdeploy@3.1.8

**Comment by shannah** [comment]
This is a puzzler.  3.1.8 is the latest, but that stacktrace doesn't line up with the source in 3.1.8.  The stacktrace appears to be from 3.1.7.

**Comment by electronstudio** [comment]
Suggest putting version number in the app itself.

Does this help?

```
> md5sum /usr/local/lib/node_modules/jdeploy/bin/JDeploy.jar
9563fe236f62cd694b0bdafb58cafae1  /usr/local/lib/node_modules/jdeploy/bin/JDeploy.jar
```

**Comment by shannah** [comment]
Try running `sudo npm install -g jdeploy` again.

**Comment by electronstudio** [comment]
ok i tried that, and uninstalling and reinstalling, but still same jar file and same exception

**Comment by shannah** [comment]
All of the accesses to `documentTypes` in the codebase are guarded so this exception cannot be happening anymore.  If similar issues occur, post the new stacktrace and open a new issue.
