### ISSUE TITLE
Local jdeploy crashes

### ISSUE THREAD

**Issue by Folcon** [shannah/jdeploy#45]
Hey, I just had this happen when installing jdeploy as a local package and then running `./node_modules/jdeploy/bin/jdeploy`

```shell
 ./node_modules/jdeploy/bin/jdeploy.js
Launching shellmarks gui.  Use jdeploy -help for help
Exception in thread "AWT-EventQueue-0" org.json.JSONException: JSONObject["name"] not found.
        at org.json.JSONObject.get(JSONObject.java:580)
        at org.json.JSONObject.getString(JSONObject.java:867)
        at ca.weblite.jdeploy.gui.JDeployProjectEditor.show(JDeployProjectEditor.java:298)
        at ca.weblite.jdeploy.JDeploy.lambda$main$0(JDeploy.java:1867)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by shannah** [comment]
If you don't have a package.json file yet, it will create one with all the needed keys.  Unfortunately, because you installed it locally, it generated a package.json file for that installation.  jdeploy is reading that and it's missing a bunch of stuff.

This is still a bug, because it should be able to handle malformed package.json files.  Will fix this on my next pass.

**Comment by Folcon** [comment]
So for a workaround I should just delete the package.json I assume?
