### ISSUE TITLE
Add support for private npm packages

### ISSUE THREAD

**Issue by FelipeAumannRS** [shannah/jdeploy#79]
Simply put, in order to deploy a package version you just type _jdeploy_ and click on publish, which works with _npm publish_ and _jpackage publish_ as well. Although, when trying to bundle locally with _jdeploy package_ within an npm private package set in the _name_ field of the _package.json_, it prompted the following error:

`C:\Users\UserName\Desktop\ProjectName>jdeploy package
Includes: [CopyRule{dir=target, includes=[ProjectJar.jar], excludes=null}]
Since JavaFX will be provided, we are stripping it from the build jar
If this causes problems you can disable this by setting stripJavaFXFiles to false in the jdeploy object of your package.json file.
Setting up codesigning
shouldSign=false, shouldNotarize=false
app dir exists = true
Icon File: C:\Users\UserName\Desktop\ProjectName\jdeploy\bundles\mac\@email_of_the_private_package_owner\application_name.app\Contents\icon.png
Processing the info plist
Processing the app.xml file
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\UserName\Desktop\ProjectName\jdeploy\releases\mac\@email_of_the_private_package_owner\application_name.tar.gz (The system cannot find the path specified)
        at ca.weblite.jdeploy.JDeploy.main(JDeploy.java:2012)
Caused by: java.io.FileNotFoundException: C:\Users\UserName\Desktop\ProjectName\jdeploy\releases\mac\@email_of_the_private_package_owner\application_name.tar.gz (The system cannot find the path specified)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:123)
        at ca.weblite.jdeploy.appbundler.Util$TAR.getTarArchiveOutputStream(Util.java:209)
        at ca.weblite.jdeploy.appbundler.Util$TAR.compress(Util.java:176)
        at ca.weblite.jdeploy.appbundler.Util.compressAsTarGz(Util.java:70)
        at com.joshondesign.appbundler.mac.MacBundler.start(MacBundler.java:226)
        at ca.weblite.jdeploy.appbundler.Bundler.runit(Bundler.java:198)
        at ca.weblite.jdeploy.JDeploy.bundle(JDeploy.java:1452)
        at ca.weblite.jdeploy.JDeploy.macBundle(JDeploy.java:1396)
        at ca.weblite.jdeploy.JDeploy.allBundles(JDeploy.java:1423)
        at ca.weblite.jdeploy.JDeploy._package(JDeploy.java:1649)
        at ca.weblite.jdeploy.JDeploy.main(JDeploy.java:1990)`

Again, that's happening probably due to the _name_ field of the _package.json_, which has a bar "/" in it:

`"license": "ISC",
    "name": "@npm_user_name/application_name",
    "files": ["jdeploy-bundle"],
    "scripts": {"test": "echo \"Error: no test specified\" && exit 1"},`

Same happens using 

> npm init --scope=@my-username
[https://docs.npmjs.com/creating-and-publishing-private-packages](url)

To put in simple words:
_**Problem:**_ Being able to publish to a npm private package with _npm publish_ but that messes up with jdeploy package (building executables locally)
**_Question:_** How can I bundle locally with a private package set?

Oddly enough, my application (which was in version 1.4.15) could get the 1.4.16 update (public package) but not the 1.4.17 (private package)

![image](https://user-images.githubusercontent.com/26864246/201462860-f7cd37f9-be72-4fa1-919b-70a4e836e21e.png)

The very same terminal prompt error happens when publishing from jdeploy UI (again, note I'm publishing to a private npm package, as demonstrated above, its done by @your_npm_username/npm_package_name, normally in the name field you just put the npm_package_name)
![image](https://user-images.githubusercontent.com/26864246/201463327-d7204a7c-43bf-452a-b657-1106a476862e.png)

**_EDIT:_**

GitHub code formatting sucks on terminal prompts and json, which is the provided output, respectively, I suggest just copping/pasting the code in a text formatting tool, such as VS code

Btw, I'm willing to connect with someone to take a closer look at that, as jdeploy being able to get updates from private packages would be a great addition (at this point it seems that only a "/" is unabling this feature to work)

**Comment by shannah** [comment]
Thanks for posting this.  Private npm packages aren't supported yet.  This has been on my mind for a while, but haven't had a chance to solve it.  It's a little bit more than having to deal with the "/" in the package name.  I'd need to provide a way to authenticate for downloads also.

This is part of a bundle of features that are on my list that relate loosely to enterprise-level features.

**Comment by FelipeAumannRS** [comment]
@shannah  Is there an email that I can subscribe to get jDeploy news or something? Cause I definitely would use it as soon it gets available
