### ISSUE TITLE
Github action was working but now it is not

### ISSUE THREAD

**Issue by electronstudio** [shannah/jdeploy#90]
I setup publishing from a private Github repo.  Pushing to my master branch created installers that worked.  Then the installers stopped working, with this error:

    findInstallFilesDir():
    Found client4.launcher.path property: /tmp/tmp.AulBv6mk6W/StrikerControl Installer-@master_25AQ.bin
    java.io.IOException: Cannot load app info because the app.xml file could not be found
      at ca.weblite.jdeploy.installer.Main.loadAppInfo(Main.java:180)
      at ca.weblite.jdeploy.installer.Main.run0(Main.java:489)
      at ca.weblite.jdeploy.installer.Main.run(Main.java:337)
      at ca.weblite.jdeploy.installer.Main.main(Main.java:322)
      
So I tried doing a tagged release.  This produced installers that fail with a different error:

    findInstallFilesDir():
    java.lang.StringIndexOutOfBoundsException: begin 19, end 14, length 14
            at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
            at java.base/java.lang.String.substring(Unknown Source)
            at java.base/java.lang.String.substring(Unknown Source)
            at ca.weblite.jdeploy.installer.npm.NPMRegistry.getPackageUrl(NPMRegistry.java:34)
            at ca.weblite.jdeploy.installer.npm.NPMRegistry.loadPackage(NPMRegistry.java:26)
            at ca.weblite.jdeploy.installer.Main.loadNPMPackageInfo(Main.java:107)
            at ca.weblite.jdeploy.installer.Main.loadAppInfo(Main.java:199)
            at ca.weblite.jdeploy.installer.Main.run0(Main.java:489)
            at ca.weblite.jdeploy.installer.Main.run(Main.java:337)
            at ca.weblite.jdeploy.installer.Main.main(Main.java:322)

**Comment by shannah** [comment]
Looks like there was a problem with the release I made yesterday.  I have pushed a new release.  If you make another build, it should work.  (i.e. just make a commit to trigger a new github action run, then try the resulting installer).

Please let me know if this fixes it for you.

**Comment by electronstudio** [comment]
Seems to work, thanks.

**Comment by electronstudio** [comment]
jdeploy 4.0.20 windows installer again says "Cannot load app info because the app.xml file could not be found".  Not sure which versions are affected, I have reverted back to 4.0.1 which works.

**Comment by shannah** [comment]
I don't think this error is related to the jdeploy version.  Sometimes there seems to be a propagation delay when publishing a new version on github and it causes it to fail when trying to load some of the files from github releases.  This delay is short, so that it should just resolve itself within minutes if this happens.
